Deployment:
  image: ruby:latest
  stage: deploy
  before_script:
    - pip install -r requirements.txt
    - python manage.py migrate
    - gem install dpl

  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --app-key=$HEROKU_API_KEY # floating-shelf-52247 # 025e5fe7-35d0-4b14-b772-f893af2c6981
  evironment:
    name: master
    url: $HEROKU_APP_HOST # floating-shelf-52247.heroku.com
  only:
    - master                                      
                                                      
